### ISSUE TITLE
RMail and malformed UTF-8 headers

### ISSUE THREAD

**Issue by gauteh** [sup-heliotrope/rmail-sup#2]
https://github.com/sup-heliotrope/sup/issues/205

**Comment by gauteh** [comment]
Another insidence: http://pastie.org/8675007 reported through #sup:

```
--- Encoding::CompatibilityError from thread: poll after loading inbox
incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/header.rb:81:in `=~'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/header.rb:81:in `parse'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:233:in `block in parse_header'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:229:in `each'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:229:in `parse_header'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:194:in `parse_low'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:183:in `parse'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:331:in `parse'
/var/lib/gems/1.9.1/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:345:in `read'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/message.rb:479:in `message_to_chunks'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/message.rb:460:in `block in message_to_chunks'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/message.rb:460:in `map'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/message.rb:460:in `message_to_chunks'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/message.rb:263:in `load_from_source!'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/message.rb:360:in `build_from_source'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:204:in `block in poll_from'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/maildir.rb:150:in `block in poll'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/maildir.rb:149:in `each'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/maildir.rb:149:in `each_with_index'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/maildir.rb:149:in `poll'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:201:in `poll_from'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:136:in `each'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:136:in `block in do_poll'
<internal:prelude>:10:in `synchronize'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:135:in `do_poll'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/util.rb:649:in `method_missing'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/modes/poll_mode.rb:15:in `poll'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:58:in `poll_with_sources'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/poll.rb:94:in `poll'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup/util.rb:649:in `method_missing'
/var/lib/gems/1.9.1/gems/sup-0.15.3/bin/sup:220:in `block (2 levels) in <module:Redwood>'
/var/lib/gems/1.9.1/gems/sup-0.15.3/lib/sup.rb:87:in `block in reporting_thread'
```
